- hosts: localhost
  sudo: yes
  tasks:
      - name: update and upgrade apt packages
        become: true
        apt:
          upgrade: yes
          update_cache: yes
          cache_valid_time: 86400

      - name: Install apache2
        apt: name=apache2 update_cache=yes state=latest cache_valid_time=86400


      - name: Start service Apache2
        service:
          name: apache2
          state: started

      - name: Install mySQL client
        apt: name=mysql-client update_cache=yes state=latest cache_valid_time=86400

      - name: Install PHP
        apt:  name=php state=present
        with_items:
             -libapache2-mod-php
             -php-mysql
             -php7.1-cli
             -php7.1-curl
             -php7.1-gd

      - name: create target directory
        file: path=/var/www/html state=directory mode=0755

      - name: deploy index.html
        become: yes
        become_user: root
        copy:
          src: index.html
          dest: /var/www/html/index.html

      - name: create _css target directory
        file: path=/var/www/html/_css state=directory mode=0755

      - name: deploy styles.css
        become: yes
        become_user: root
        copy:
          src: _css/styles.css
          dest: /var/www/html/_css/styles.css
          
      - name: deploy apache.conf
        become: yes
        become_user: root
        copy:
          src: apache2.conf
          dest: /etc/apache2/apache2.conf